server:
  port: 8761 # Puerto donde se ejecutará el Eureka Server

eureka:
  client:
    register-with-eureka: false # El servidor no se registra a sí mismo
    fetch-registry: false       # El servidor no necesita obtener el registro
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false
  instance:
      hostname: localhost

spring:
  application:
      name: eureka-server
